# Generated by Django 3.2.24 on 2024-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0002_auto_20240302_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
